server {
    listen 443 ssl http2;
    server_name bacolod.com www.bacolod.com;
    ssl_certificate /etc/letsencrypt/live/domain-sales-origin.winterwind.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain-sales-origin.winterwind.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/www/city/public;
    index index.php;
    charset utf-8;
    client_max_body_size 6m;
    access_log /var/log/nginx/city-access.log;
    error_log /var/log/nginx/city-error.log;
    location / { try_files $uri /index.php?$query_string; }
    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param HTTPS on;
        fastcgi_pass 127.0.0.1:9084;
    }
    location ^~ /storage/ { alias /var/www/city/storage/app/public/; add_header X-Content-Type-Options nosniff; }
    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
}
