<?php
namespace App\Http\Controllers;
use App\Models\{Category,City,Listing,Submission};
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
class SubmissionController {
 public function dashboard(Request $r,City $city){$listings=Listing::forCity($city)->where('owner_id',$r->user()->id)->with('category')->orderBy('name')->get();$submissions=Submission::where('city_id',$city->id)->where('user_id',$r->user()->id)->with('listing')->latest()->paginate(15);return view('dashboard',compact('listings','submissions'));}
 public function form(Request $r,City $city,?string $slug=null){$listing=$slug ? Listing::forCity($city)->published()->where('slug',$slug)->firstOrFail() : null;$type=$r->query('type','new');abort_unless(in_array($type,['new','edit','claim','correction']),404);abort_if(!$listing && $type!=='new',404);if($listing && $type==='new'){abort(404);}if($type==='edit'){abort_unless($listing->owner_id===$r->user()?->id || $r->user()?->is_admin,403);}if($type==='claim'){abort_unless($listing->kind==='business' && !$listing->owner_id,403);}$categories=Category::when($listing?->kind==='public_place',fn($q)=>$q->where('slug','places-to-explore'),fn($q)=>$q->where('slug','!=','places-to-explore'))->orderBy('position')->get();return view('submission',compact('listing','type','categories'));}
 public function store(Request $r,City $city){$base=$r->validate(['type'=>'required|in:new,edit,claim,correction','listing_id'=>['nullable','integer',Rule::exists('listings','id')->where('city_id',$city->id)->where('status','published')],'company_website'=>'prohibited']);$type=$base['type'];$listing=isset($base['listing_id']) ? Listing::forCity($city)->findOrFail($base['listing_id']) : null;abort_unless(($type==='new' && !$listing)||($type!=='new' && $listing),422);
  if($type==='edit'){abort_unless($listing->owner_id===$r->user()->id || $r->user()->is_admin,403);}
  if($type==='claim'){abort_unless($listing->kind==='business' && !$listing->owner_id,403);$data=$r->validate(['relationship'=>'required|string|max:150','evidence'=>'required|string|min:30|max:3000','contact_email'=>'required|email|max:254']);}
  elseif($type==='correction'){$data=$r->validate(['details'=>'required|string|min:15|max:3000']);}
  else {$data=$r->validate(['name'=>'required|string|max:160','category_id'=>['required','integer',Rule::exists('categories','id')->where(fn($q)=>$listing?->kind==='public_place' ? $q->where('slug','places-to-explore') : $q->where('slug','!=','places-to-explore'))],'description'=>'required|string|min:40|max:2500','address'=>'required|string|max:255','area'=>'required|string|max:80','website'=>'nullable|url:http,https|max:1000','phone'=>['nullable','string','max:50','regex:/^[+0-9 ().\-]+$/'],'tags'=>'nullable|array|max:5','tags.*'=>'in:family,date-night,friends,rainy-day,weekend','photo'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:4096|dimensions:max_width=6000,max_height=6000','photo_rights'=>'required_with:photo|accepted']);$data['tags']=$data['tags']??[];unset($data['photo'],$data['photo_rights']);if($r->hasFile('photo')){$data['photo_path']=$r->file('photo')->store('listings/'.$city->id,'public');$data['photo_credit']='Provided by the business';}}
  if(Submission::where('city_id',$city->id)->where('user_id',$r->user()->id)->where('type',$type)->where('listing_id',$listing?->id)->where('status','pending')->exists()){return back()->withErrors(['form'=>'You already have this kind of request awaiting review. Check your dashboard.']);}
  Submission::create(['city_id'=>$city->id,'listing_id'=>$listing?->id,'user_id'=>$r->user()->id,'type'=>$type,'payload'=>$data]);return redirect('/dashboard')->with('success','Your request has been saved for review. You can follow its status here.');
 }
}
